services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=88888888
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
  backend:
    image: backend
    ports:
      - "3000:3000"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=88888888
      - PG_DATABASE=postgres
    depends_on:
      - db
  frontend1:
    image: frontend1
    ports:
      - "8080:80"
  frontend2:
    image: frontend2
    ports:
      - "8081:80"
volumes:
  db:
